project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - CNAME

website:
  title: "Candy's Comedy"
  site-url: https://candyscomedy.com
  navbar: false

format:
  html:
    theme: none
    css: styles.css
    toc: false
    title-block: false
    include-in-header: resources/fonts.html
